---
- name: create a sandbox instance
  hosts: localhost
  gather_facts: false
  vars:
    keypair: id_rsa
    instance_type: t2.micro
    image: ami-e41b618b
    region: ap-south-1
  tasks:
    - name: Launch Instance
      ec2:
        key_name: "{{ keypair }}"
        group: default
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        count: 1
        aws_access_key: <<IAM user access key>>
        aws_secret_key: <<IAM user secret key>>
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2